### ISSUE TITLE
Setup a proper email address

### ISSUE THREAD

**Issue by AJizzleBizzle** [cohen990/VoxPop#119]
We are currently having emails addressed to admin@VOXPOP.london being forwarded to us. 

- We need to set up a few proper accounts info@, admin@ etc with our domain name for replying to users and setting up services etc. 

- Gmail/MS not possible for free anymore as far as I know - [other suggestions] (http://colorlabsproject.com/blog/4-free-email-providers-custom-domain/)

**Comment by cohen990** [comment]
dont care, wont fix
